name = "motherindiatourtravels-images"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "motherindiatourtravels-assets"

[observability.logs]
enabled = false
invocation_logs = true